### ISSUE TITLE
Building Issue

### ISSUE THREAD

**Issue by fancythedeveloper** [sonicretro/skc-mod-loader#1]
When I try to build the master source code, I get errors related to "IniCollection".
I'm using VS 2015 Community Edition.

Here's the output:
1>------ Rebuild All started: Project: SKCModLoader, Configuration: Debug Win32 ------
2>------ Rebuild All started: Project: SKCModManager, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: MusicConfigTool, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\mod-loader-common\ModManagerCommon\ModManagerCommon.csproj' does not exist.
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(464,61,464,65): error CS1026: ) expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(464,65,464,66): error CS1002: ; expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(464,65,464,66): error CS1513: } expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(549,37,549,43): error CS1026: ) expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(549,43,549,44): error CS1002: ; expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(549,43,549,44): error CS1513: } expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(594,37,594,43): error CS1026: ) expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(594,43,594,44): error CS1002: ; expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(594,43,594,44): error CS1513: } expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(599,76,599,89): error CS1026: ) expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(599,89,599,90): error CS1002: ; expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(599,89,599,90): error CS1513: } expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(599,91,599,93): error CS1525: Invalid expression term '||'
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(599,118,599,119): error CS1002: ; expected
2>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\SKCModManager\MainForm.cs(599,118,599,119): error CS1513: } expected
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\mod-loader-common\ModManagerCommon\ModManagerCommon.csproj' does not exist.
3>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\MusicConfigTool\MainForm.cs(1,7,1,14): error CS0246: The type or namespace name 'IniFile' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\MusicConfigTool\MainForm.cs(332,4,332,17): error CS0246: The type or namespace name 'IniCollectionAttribute' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\MusicConfigTool\MainForm.cs(332,4,332,17): error CS0246: The type or namespace name 'IniCollection' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\MusicConfigTool\MainForm.cs(332,18,332,35): error CS0103: The name 'IniCollectionMode' does not exist in the current context
3>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\MusicConfigTool\MainForm.cs(338,4,338,17): error CS0246: The type or namespace name 'IniCollectionAttribute' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\MusicConfigTool\MainForm.cs(338,4,338,17): error CS0246: The type or namespace name 'IniCollection' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\Lazala Hane Fmly\Downloads\skc-mod-loader-master\MusicConfigTool\MainForm.cs(338,18,338,35): error CS0103: The name 'IniCollectionMode' does not exist in the current context
========== Rebuild All: 0 succeeded, 3 failed, 0 skipped ==========

**Comment by michael-fadely** [comment]
`git submodule update --init --recursive`

**Comment by fancythedeveloper** [comment]
I'm confused. Whatever, I'm installing Git for Windows right now.
(Oh NVM, gonna do it in Visual Studio now.)

**Comment by MainMemory** [comment]
Well I guess we can close this now.

**Comment by fancythedeveloper** [comment]
Yay?

**Comment by MainMemory** [comment]
Well you never replied with your results, am I just supposed to leave it open forever?

**Comment by fancythedeveloper** [comment]
Not really.

**Comment by MainMemory** [comment]
Well, did you get it to build?
